---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metallb-node-route-agent.fullname" . }}
  labels:
    {{- include "metallb-node-route-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
   foo: bar
{{- with .Values.configMapData }}
{{- toYaml . | nindent 2 }}
{{- end }}
